import type { CustomerProfile, LikedStore, SharedItem, CustomerStat } from "../types/types";

export const initialCustomerProfile: CustomerProfile = {
  name: "Drake Delos Reyes",
  email: "drake.delosreyes@shopscout.app",
  avatarUrl: "/drake-profile.jpg",
  memberSince: "March 2025",
  savedDealsCount: 12,
};

export const initialLikedStores: LikedStore[] = [
  {
    id: "store-1",
    name: "Sneaker Hub Cebu",
    brand: "Nike & Adidas",
    category: "Footwear & Apparel",
    rating: 4.8,
    reviewsCount: 142,
    address: "Ayala Center Cebu, Level 2",
    distanceKm: 0.8,
    isOpen: true,
    imageUrl: "https://images.unsplash.com/photo-1552346154-21d32810aba3?w=500&auto=format&fit=crop&q=80",
    likedAt: "2 days ago",
    featuredDeal: "20% OFF on Air Jordan series",
    lat: 10.3157,
    lng: 123.8854,
  },
  {
    id: "store-2",
    name: "Urban Kicks Co.",
    brand: "Puma & New Balance",
    category: "Streetwear",
    rating: 4.6,
    reviewsCount: 89,
    address: "SM City Cebu, Ground Floor",
    distanceKm: 1.4,
    isOpen: true,
    imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&auto=format&fit=crop&q=80",
    likedAt: "1 week ago",
    featuredDeal: "Buy 1 Get 1 on Socks",
    lat: 10.3120,
    lng: 123.9185,
  },
  {
    id: "store-3",
    name: "Sole Academy Studio",
    brand: "Converse & Vans",
    category: "Lifestyle Sneakers",
    rating: 4.9,
    reviewsCount: 215,
    address: "IT Park, Central Bloc",
    distanceKm: 2.1,
    isOpen: false,
    imageUrl: "https://images.unsplash.com/photo-1607522370275-f14206abe5d3?w=500&auto=format&fit=crop&q=80",
    likedAt: "2 weeks ago",
    featuredDeal: "Free Waterproof Spray with purchase",
    lat: 10.3282,
    lng: 123.9061,
  },
  {
    id: "store-4",
    name: "Runners Peak",
    brand: "Asics & Hoka",
    category: "Athletic & Performance",
    rating: 4.7,
    reviewsCount: 64,
    address: "Banilad Town Centre",
    distanceKm: 3.5,
    isOpen: true,
    imageUrl: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=500&auto=format&fit=crop&q=80",
    likedAt: "3 weeks ago",
    featuredDeal: "Free Gait Analysis weekend",
    lat: 10.3400,
    lng: 123.9100,
  },
];

export const initialSharedItems: SharedItem[] = [
  {
    id: "share-1",
    title: "Sneaker Hub Cebu - 20% OFF Air Jordan",
    storeName: "Sneaker Hub Cebu",
    category: "Store Deal",
    sharedUrl: "https://shopscout.app/store/sneaker-hub-cebu?ref=alex_m",
    sharedAt: "Yesterday at 4:15 PM",
    platform: "WhatsApp",
    clicksCount: 38,
    imageUrl: "https://images.unsplash.com/photo-1552346154-21d32810aba3?w=500&auto=format&fit=crop&q=80",
    notes: "Sent to the Sneakerhead group chat",
  },
  {
    id: "share-2",
    title: "Urban Kicks Co. New Stock Drop",
    storeName: "Urban Kicks Co.",
    category: "Store Profile",
    sharedUrl: "https://shopscout.app/store/urban-kicks-co?ref=alex_m",
    sharedAt: "3 days ago",
    platform: "Copy Link",
    clicksCount: 19,
    imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&auto=format&fit=crop&q=80",
    notes: "Shared via personal message",
  },
  {
    id: "share-3",
    title: "Sole Academy Limited Edition Release",
    storeName: "Sole Academy Studio",
    category: "Event Deal",
    sharedUrl: "https://shopscout.app/store/sole-academy?ref=alex_m",
    sharedAt: "5 days ago",
    platform: "Facebook",
    clicksCount: 52,
    imageUrl: "https://images.unsplash.com/photo-1607522370275-f14206abe5d3?w=500&auto=format&fit=crop&q=80",
    notes: "Posted on Facebook timeline",
  },
];

export const initialCustomerStats: CustomerStat[] = [
  {
    label: "Liked Stores",
    value: 4,
    trend: "+2 this month",
    description: "Favorites saved for quick access",
  },
  {
    label: "Shared Links",
    value: 3,
    trend: "109 total clicks",
    description: "Deals & stores shared with friends",
  },
  {
    label: "Active Deals Saved",
    value: 12,
    trend: "3 expiring soon",
    description: "Exclusive coupons & promos",
  },
  {
    label: "Total Engagement",
    value: "109",
    trend: "+24% week over week",
    description: "Clicks generated from your shares",
  },
];
